### ISSUE TITLE
Hello， when I clicked the close button of Sales Notification, it dont appear again

### ISSUE THREAD

**Issue by li2020rich** [WPDevelopers/notificationx#109]
Hello， I installed the free version on my website, a woocommerce website, I set up a Sales Notification and everything started fine. When I clicked the close button once, it never appeared again. I refreshed the web page to no avail. I used Google Chrome to open an incognito page before it appeared again. Where can I set it? How to solve this problem? Thanks

**Comment by NayeemNipun** [comment]
Hi **@li2020rich**,
Greetings. Hope you are doing well. 

Regarding your query, in NotificationX if users click the close button from the notification then it will not show on the same browser for 24 hours unless the cache of the browser is cleared. Or it will show on the incognito mode immediately. This is how NotificationX works. 

I would like to suggest you to clear your browser cache if you click the close button from the notification. 

Hope you understand. Please feel free to reach out anytime you have issues or queries. We are always here to assist you. 

Thanks and Regards.

**Comment by li2020rich** [comment]
Hello, dear friend, Thank you for your answer. Before you answer, I tested it for about an hour or two. I thought there was a conflict with my other plug-ins or scripts, but I found that there was no conflict.


Honestly, I think this plugin is great. But I found that my competitor also had a similar sales booster, but after I clicked to close it, it started to display again after a while. This is why I came to you. Is it possible to add a setting option in the settings in the future? For example, can I let it display again after a while, or let it display after 24 hours? Thank you very much for your time.




Best regards


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WPDevelopers/notificationx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月24日(星期天) 晚上11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WPDevelopers/notificationx] Hello， when I clicked the close button of Sales Notification, it dont appear again (Issue #109)





 
Hi @li2020rich,
 Greetings. Hope you are doing well.
 
Regarding your query, in NotificationX if users click the close button from the notification then it will not show on the same browser for 24 hours unless the cache of the browser is cleared. Or it will show on the incognito mode immediately. This is how NotificationX works.
 
I would like to suggest you to clear your browser cache if you click the close button from the notification.
 
Hope you understand. Please feel free to reach out anytime you have issues or queries. We are always here to assist you.
 
Thanks and Regards.

**Comment by li2020rich** [comment]
Hello,&nbsp;




Regarding your query, in NotificationX if users click the close button from the notification then it will not show on the same browser for 24 hours unless the cache of the browser is cleared. Or it will show on the incognito mode immediately. This is how NotificationX works.
----&gt;It's been more than 24 hours since I clicked the close button, why doesn't it still show up? Thanks.




Best regards


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WPDevelopers/notificationx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月24日(星期天) 晚上11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WPDevelopers/notificationx] Hello， when I clicked the close button of Sales Notification, it dont appear again (Issue #109)





 
Hi @li2020rich,
 Greetings. Hope you are doing well.
 
Regarding your query, in NotificationX if users click the close button from the notification then it will not show on the same browser for 24 hours unless the cache of the browser is cleared. Or it will show on the incognito mode immediately. This is how NotificationX works.
 
I would like to suggest you to clear your browser cache if you click the close button from the notification.
 
Hope you understand. Please feel free to reach out anytime you have issues or queries. We are always here to assist you.
 
Thanks and Regards.

**Comment by li2020rich** [comment]
Hi support team, it didn't pop up again until I clicked the close button. You told me before that it will appear again after 24 hours, but it never appears on my side. Is it my problem? Thanks
