### ISSUE TITLE
Notification Is Not Linked

### ISSUE THREAD

**Issue by SooBahkDo** [WPDevelopers/notificationx#61]
I am a bit confused about the LINK in settings. Is the link configured there supposed to be connected to the Notification so when a user clicks the notification they are directed to the LINK page?

If that is the intent (which is not clear in the documentation) then it does not appear to work.

**Comment by priyomukul** [comment]
Yes, the link is configured to redirect user, to the link in notification. 

version 1.3.1 should fix the issue. Feel free to give feedback if anything goes wrong or links not working

Thanks for your feedback.
