### ISSUE TITLE
Feature To Import Notifications

### ISSUE THREAD

**Issue by SooBahkDo** [WPDevelopers/notificationx#63]
It would be great to be able to import a series of generic notifications via xls or csv file.

In a use case where the type of notifications may not be sales or conversion related, it would be great to  be able to import a group of notifications.

Some sites may want to cycle through a series of short announcements about things published on the site.

A more flexible modified notification theme would be needed as well.

**Comment by priyomukul** [comment]
Such a great features it will be. we have this in our planing list. 

Hope it will be available in next 1.* major update. 

Thanks for your feedback.

**Comment by NahidHasanTushar1** [comment]
Hi @SooBahkDo, 

Hope you're doing well 😊. 

We're so glad to inform you that we have already implemented the **import/export** feature in our NotificationX plugin. You'll get some details here: https://notificationx.com/docs/notificationx-import-export/

Thank you!
