### ISSUE TITLE
BUG: Deletes All Saved Image URLS On Custom Notification Content

### ISSUE THREAD

**Issue by SooBahkDo** [WPDevelopers/notificationx#65]
This has happended 3 different times.

I created a set of notifications and manually attached images for the customers.
Upon saving and publishing all worked as expected.

Later I added additional notifications to the set and one did not have a photo.
Upon saving all photos on all notifications were deleted.
The default image displayed for all notifications.
Upon inspecting each notification the url to the image was blank.
After reselecting each image for each notification and saving and publishing the notifications all worked as expected.

Later I added additional notifications and one did not have an image when I saved and published.  
Once again all images on all notifications were deleted.
I had to manually reattach each image to each notification.
After reattaching all images and making sure that no notification was missing an image, I published them and they are working as expected.

There seems to be a bug.

**Comment by shamserSuzon** [comment]
Hi @SooBahkDo 

I have tried to reproduce the issue in my local setup as per your given description but I couldn't make it happen. It's working fine here. Please, make sure, you are using the latest version of the plugin.

Thanks.

**Comment by SooBahkDo** [comment]
I will document exact steps to recreate issue and report back,

**Comment by shamserSuzon** [comment]
Hi @SooBahkDo 

I haven't heart back from you yet on this issue. I am considering the issue as resolved. If you face the same problem again, you can reopen this ticket again.

Thanks.
