### ISSUE TITLE
Mispelling Issue Persists in V 1.35 free and 1.29 pro

### ISSUE THREAD

**Issue by SooBahkDo** [WPDevelopers/notificationx#71]
Notifications still display a mispelling in versions 1.35 free and 1.29 pro.

"SometimeS ago"  should be "Sometime ago"  without the extra S

Refer to screenshot

![notifications-mispelling2-2019-09-19_1233](https://user-images.githubusercontent.com/3432950/65275498-abb4f680-dada-11e9-9b6a-dd6407f0494e.png)

**Comment by priyomukul** [comment]
Hey there ... 

please check this https://d.pr/free/i/wvo71p 

after selecting `Sometimes ago` there is an extra field poped up... you can change text now. 

Please check it.

**Comment by SooBahkDo** [comment]
That works well.

Thanks!
