### ISSUE TITLE
Hide notification from mobile

### ISSUE THREAD

**Issue by Aaenics** [WPDevelopers/notificationx#76]
The button that says "hide notification from mobile doesnt seem to work"
even when you click it and saved it still shows the comment popup notifications to users and visitors
and its too huge and covers so much sapce.
Notification X is really great and I look foward to seeing these fixes

**Comment by priyomukul** [comment]
Sorry for the inconvenience. 

I will check the issue and fix it for you. 

Thanks for using NotificationX.

**Comment by priyomukul** [comment]
Hey @Aaenics, 

Can you please give me your website link? 

So that I can take a look. 

Regards.

**Comment by priyomukul** [comment]
Hey @Aaenics 

I tried to reproduce it with the Released version of NotificationX, but I couldn't.

Seems working fine. 

Can you please create a ticket in support with some more details to look at.

Regards
