### ISSUE TITLE
Feature to override template files

### ISSUE THREAD

**Issue by codewp** [WPDevelopers/notificationx#80]
Hi

Thank you for this useful plugin.

I found that pressbar template file is not overridable because gets the template file from the default location.
`plugin_dir_path( __FILE__ ) . 'press-bar-frontend.php';`
If it is possible for you please add a feature to the plugin to allow developers to override the template files as the WooCommerce do.

**Comment by priyomukul** [comment]
Sorry for late reply. 

Now we have `elementor` implemented with Press Bar from Nx `v1.9.2`, so that your can design your own bar with `Elementor`. 

Thanks. (Making this issue completed), If you face any issue in future, please let us know.
