### ISSUE TITLE
Notification X Pro - menu items not appearing

### ISSUE THREAD

**Issue by gleave75** [WPDevelopers/notificationx#81]
Menu items don't appear when Pro is activated. They do appear when Pro is not activated. Have confirmed licence code is entered an active.

Only items able to be accessed are settings, and Analytics. All caches have been cleared and checked.
![Screen Shot 2020-10-07 at 7 27 50 pm](https://user-images.githubusercontent.com/11733146/95313217-3b3e6a80-08d3-11eb-98a7-69db167555e8.png)

**Comment by priyomukul** [comment]
It's should not be like this, can please give me some details about your site? 

for example, Your plugin list, theme list, etc.

Need to check if there is any conflict with other plugins which is not appropriate.

**Comment by gleave75** [comment]
Hi Priyo,

 

Thanks for the quick reply.

 

I have the unlimited developer licence so I’ve done the following:

 

The site is running a large number of plugins, most of which are premium paid, and up to date but it is my intention to audit the site and reduce the number needed. The site uses Elementor and uses their hello theme.

 

 However, I have also checked on a duplication of the site with every plugin deactivated other than WooCommerce, running TwentyTwenty, and finally on another duplicate with all the plugins deleted, so just Notification X & Pro and WooCommerce with TwentyTwenty and the same issue occurs with the menu.

 

Happy to give you a login for that site as it’s not the live site.

**Comment by khan-rafin-ahmed** [comment]
@gleave75,

Hi, there. Very strange issue. We will have to investigate your site to see what's happening. So, please provide admin access of your website in this email address: support[at]wpdeveloper[dot]net

Thank you!

**Comment by gleave75** [comment]
Thank you.

 

Here are the login credentials for the test site I have:

 

https://woocommerce-93588-1527635.cloudwaysapps.com/wp-admin/

 

 

Citrus Design

 

avesU^gXdjEGbfF1x4sUVKD2

 

Thanks

**Comment by khan-rafin-ahmed** [comment]
@gleave75,

Thanks for the admin access but never share it on a public forum like this again. I have deleted your previous comment. We will look into this and will get back to you soon.

Thank you!

**Comment by gleave75** [comment]
Sorry – thought I had just replied via email to you. I didn’t even realise it was public.

**Comment by khan-rafin-ahmed** [comment]
@gleave75,

Sorry for the delayed response. However, we have pushed a fix on your site and it's resolved now. Menu is appearing as expected with NotificationX Pro activated. Check out this screenshot: https://d.pr/i/cX3yb7

For faster support, I would recommend you to contact us here: wpdeveloper.net/support/new-ticket/

Thank you!
