### ISSUE TITLE
Nothing is showing while configuring the notifications

### ISSUE THREAD

**Issue by prkarthik** [WPDevelopers/notificationx#83]
![Edit-‹-Granniez-Green-Herbs-—-WordPress](https://user-images.githubusercontent.com/2854679/97157296-e9845400-179d-11eb-85df-5e68209ab243.png)

Only the bell icon is visible and no other options are visible. The JavaScript console error shows a knob() issue.

**Comment by priyomukul** [comment]
Hi @prkarthik,

Sorry for the inconvenience & late reply. 
If you still face this issue, please try our new version `2.0.2`, 

Let us know, how it goes.

Thanks.
