### ISSUE TITLE
Manual order not triggering the Sale Notifications

### ISSUE THREAD

**Issue by mdarif** [WPDevelopers/notificationx#87]
All the automated generated orders are generating the Sale Notifications message but the manual order ones.

Can someone please revert?

Thanks
Mohammad Arif

**Comment by mdarif** [comment]
Any update team?

**Comment by priyomukul** [comment]
Sorry for the delay! 

We don't have that option right now, but I have added this as a feature request. We will add it in a future version. 

Thanks.

**Comment by mdarif** [comment]
Great, thanks keep us posted about the progress.

**Comment by priyomukul** [comment]
Will be released in the next version. 

Thanks.

**Comment by priyomukul** [comment]
For now, you can try the latest branch. 

We will improve more, Our QA team is on testing.

**Comment by mdarif** [comment]
Thanks for quick turn around (y)
