### ISSUE TITLE
Content Advanced Template Issue

### ISSUE THREAD

**Issue by Linaleee** [WPDevelopers/notificationx#91]
After creating a notification, if I click edit notification at all, one line of the content advanced template gets deleted each time.
 
![Screen Shot 2021-04-29 at 12 40 06 PM](https://user-images.githubusercontent.com/83419878/116587007-0bdf6180-a8e8-11eb-8ce2-bd1815ef912b.png)

For instance, upon re-entering the edit mode, the last line `in {{city}}` will be gone. If I publish and re-enter edit mode again, `{{title}}` will disappear next.

**Comment by priyomukul** [comment]
Hey @Linaleee 
Sorry for the inconvenience. 

`This Feature` is newly developed/improved in `v2.*`, hopefully, will be fixed.

Considering this as resolved, let us know you face any issues again. 

Thanks
