### ISSUE TITLE
Not showing correctly Essential Addons widgets

### ISSUE THREAD

**Issue by monica123m** [WPDevelopers/notificationx#94]
Hi, i'm trying to put a countdown and a Fancy Text in the NotificationX bar, but it doesn't work. The widgets from Essential Addons i use don't show up. 

I tried updating elementor and essential addons without results.

**Comment by priyomukul** [comment]
Hi @monica123m,

Sorry for the inconvenience. 
Since we are not hearing from you, Considering this issue as resolved.

Let us know if you face anything new.

Thanks.
